### ISSUE TITLE
在手机上运行这个脚本报错

### ISSUE THREAD

**Issue by sunianOvO** [592767809/export_music#3]
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/export_music/main.py", line 2, in <module>
    from server import *
  File "/data/data/com.termux/files/home/export_music/server/__init__.py", line 2, in <module>
    from server import qqmusic, kugoumusic, kugoulitemusic, wangyiyunmusic, qishuimusic, xuelang, wufanyouxiting
  File "/data/data/com.termux/files/home/export_music/server/qqmusic.py", line 8, in <module>
    from utils.tc_tea import tc_tea_decrypt
ModuleNotFoundError: No module named 'utils.tc_tea'

**Comment by 592767809** [comment]
你是不是没有把整个项目都拉下去？
